### ISSUE TITLE
hello can you help for few seconds to make this work for tv 15.4 version thnx, what's ur email senpai? :D

### ISSUE THREAD

**Issue by YellowBlueBuzz** [NMSAzulX/Overtimer#1]
![image](https://user-images.githubusercontent.com/52501486/88455245-5d187b80-cea6-11ea-8d2b-10acb1d0371a.png)

**Comment by NMSAzulX** [comment]
Okay, I'll try.  This is my email: 2765968624@qq.com

**Comment by NMSAzulX** [comment]
@YellowBlueBuzz  Hello, I have push new code to dev and master. It can get id and password for teamview 15.5.6. 
```C#
var result = TeamviewOperator.GetInfos(IdName,PasswordName);
```
Result is a dictionary for {idName, xxxxxx} { PasswordName, xxxx };

![image](https://user-images.githubusercontent.com/16236903/88504832-63bf0400-d008-11ea-9e95-5d9988286029.png)
like this:
My IdName is "您的ID"
My PasswordName is "密码"。
![image](https://user-images.githubusercontent.com/16236903/88504892-8d782b00-d008-11ea-8576-0e7185af9b98.png)

**Comment by YellowBlueBuzz** [comment]
nice! thnx for being responsive gonna test it now...

**Comment by YellowBlueBuzz** [comment]
hello I have sent an email to you senpai

**Comment by NMSAzulX** [comment]
@YellowBlueBuzz  I have push a new version with .netframework 45.
